sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpcs
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.0' ]]; then php vendor/bin/phpunit ; fi
  - php vendor/bin/behat

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then travis_retry php vendor/bin/coveralls -v ; fi

cache:
  directories:
    - vendor

branches:
  only:
    - master

notifications:
  hipchat: 566ef4099050f188b543dea725b257@ci-message
